blank_issues_enabled: false
contact_links:
  - name: ðŸ™‹ Ask a question
    url: https://github.com/QuestPi/pi-platform-docs/discussions
    about: Ask questions and discuss with other community members
